### ISSUE TITLE
This rules 🎉

### ISSUE THREAD

**Issue by StephenBarlow** [EricPedley/kanyezone-bot-cpp#1]
Hi Eric! We (the [Kanye Zone people](http://www.kanyezone.com/about)) saw your bot after DevPost triggered the first Google alert for KZ in ages 😄 

We all think it's cool as hell and are honored that you picked our silly old web game to develop against. Kudos!

(Feel free to close this issue, it was the easiest way to send you a note 😄)

-Stephen

**Comment by EricPedley** [comment]
Wow! Thanks for the note. I can't believe you found this project. This made my day 😃
